# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-31 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_noti', models.CharField(max_length=30)),
                ('Notification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problem_solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('img_ans', models.FileField(null=True, upload_to='')),
                ('img_que', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rollnumber_Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('start', models.BigIntegerField()),
                ('end', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Running_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('alt_contact', models.BigIntegerField()),
                ('DOB', models.CharField(max_length=35)),
                ('course', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=25)),
                ('year', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('stu_id', models.BigIntegerField()),
                ('assignment_no', models.IntegerField()),
                ('answer', models.CharField(max_length=1000)),
                ('ans_img', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('alt_contact', models.BigIntegerField()),
                ('Address', models.CharField(max_length=35)),
                ('course', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=25)),
                ('year', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('submittion_date', models.DateField()),
                ('assignment', models.CharField(max_length=1000)),
                ('assign_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_id_Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('start', models.BigIntegerField()),
                ('end', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_subject_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.BigIntegerField()),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tech_Notes_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('Notes', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Computer_science_student',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('STC_pro_app.student',),
        ),
        migrations.CreateModel(
            name='Electrical_student',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('STC_pro_app.student',),
        ),
        migrations.CreateModel(
            name='Electronics_student',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('STC_pro_app.student',),
        ),
        migrations.CreateModel(
            name='Mechanical_student',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('STC_pro_app.student',),
        ),
    ]
